name: Godot Builder

on:
  pull_request: {}
  push:
    tags:
      - 'v*'

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win64] #, linux, mac]
    steps:
      - name: Format Tag Name
        id: replace_string
        uses: frabert/replace-string-action@v2
        with:
          pattern: '\.'
          string: ${{ github.ref_name }}
          replace-with: '_'
      - uses: actions/checkout@v2
        with:
          lfs: false
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: "Reia_${{ steps.replace_string.outputs.replaced }}.exe"
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Create Release And Upload Asset
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: build/Reia_${{ steps.replace_string.outputs.replaced }}.exe
          body: |
            # Reia - `${{ github.ref_name }}`

            ...

            ### Changes
            **Added:**
            - ...

            **Removed:**
            - ...

            **Changed:**
            - ...

            **Fixed:**
            - ...

            ----

            ...
          draft: true
          prerelease: true
