name: Zig Test

on: 
  workflow_dispatch:
  push:
    paths:
      - zig/**

env:
  VERSION: 0.13.0

jobs:
  zig_test:
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{env.VERSION}}
      - name: Generate Godot Project
        run: godot -e --path ../godot --import --headless
      - name: Generate Zig Bindings
        run: zig build bind
      - name: Test
        working-directory: ./zig
        run: zig build test
      - name: Lint
        working-directory: ./zig
        run: zig fmt --check .
      - name: Build
        working-directory: ./zig
        run: zig build
