name: Zig Test

on: 
  workflow_dispatch:
  push:
    paths:
      - zig/**

env:
  ZIG_VERSION: 0.13.0
  ZIG_PATH: ~/sdk/zig

jobs:
  godot_zig:
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      # Cache Godot Imports
      - name: Cache import assets
        uses: actions/cache@v3
        id: cache-import
        with:
          path: |
            godot/.godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      
      # Cache Zig
      - name: Cache Zig
        uses: actions/cache@v3
        id: cache-zig
        with:
          path: |
            ${{env.ZIG_PATH}}
          key: zig-${{ runner.os }}-${{ github.sha }}


      - name: Install Zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install xz-utils -y
          mkdir -p ~/sdk/zig
          mkdir -p /home/downloads
          wget https://ziglang.org/download/${{env.ZIG_VERSION}}/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -O /home/downloads/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz
          tar -xf /home/downloads/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -C ~/sdk/zig
          cp -r ~/sdk/zig/zig-linux-x86_64-${{env.ZIG_VERSION}}/* ~/sdk/zig
          rm -rf ~/sdk/zig/zig-linux-x86_64-${{env.ZIG_VERSION}}
      - name: Add Zig to PATH
        run: echo ${{env.ZIG_PATH}} >> $GITHUB_PATH
      - name: Generate Godot Project
        if: steps.cache-import.outputs.cache-hit != 'true'
        run: godot --headless --verbose --editor --quit --rendering-driver opengl3 -e ../godot
        working-directory: ./zig
      - name: Generate Zig Bindings
        working-directory: ./zig
        run: zig build bind
      - name: Test
        working-directory: ./zig
        run: zig build test
      - name: Lint
        working-directory: ./zig
        run: zig fmt --check .
      - name: Build
        working-directory: ./zig
        run: zig build
