name: Zig Test

on: 
  workflow_dispatch:
  push:
    paths:
      - zig/**

env:
  VERSION: 0.13.0

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{env.VERSION}}
      - name: Test
        working-directory: ./zig
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{env.VERSION}}
      - name: Lint
        working-directory: ./zig
        run: zig fmt --check .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{env.VERSION}}
      - name: Build
        working-directory: ./zig
        run: zig build
